[package]
name = "sd-archivemanager-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
sd-archivemanager = { path = "../sd-archivemanager/" }
xdg = "2.5.2"
